os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.2
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://apt.vapor.sh/ci; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=~/swift/usr/bin:"${PATH}"; fi
  - swift package update
  - swift build
